/**
 * Single source of truth for the version pins the scaffold writes into a
 * generated project. Every pin is DERIVED from the engine packages' own
 * manifests so a `@press/*` release can never drift from what `press create`
 * emits.
 *
 * This module is pure (no filesystem): it takes already-parsed manifests and
 * returns the pins. The build-time runner that reads the real package.json files
 * and writes the committed output lives in scripts/gen-versions.ts; the committed
 * output is src/create/versions.generated.ts; a drift test (compute-versions.test.ts)
 * fails CI if that file goes stale.
 */

/** The subset of a package.json this module reads. */
export interface Manifest {
  version: string;
  devDependencies?: Record<string, string>;
}

export interface EngineManifests {
  cli: Manifest;
  web: Manifest;
  cms: Manifest;
}

export interface ScaffoldVersions {
  pressCli: string;
  pressWeb: string;
  pressCms: string;
  next: string;
  react: string;
  strapi: string;
}

/**
 * Next has no canonical source in the engine manifests: @press/web declares only
 * an open peer range (`next: ">=15"`), which is useless as a pin. So the tested
 * Next major lives here as the single explicit knob.
 * Follow-up: add next to @press/web devDependencies and derive it here too.
 */
const NEXT_PIN = '^15.1.0';

function requireDevDep(m: Manifest, name: string, pkg: string): string {
  const range = m.devDependencies?.[name];
  if (!range) {
    throw new Error(`cannot derive "${name}" pin: ${pkg} has no devDependencies["${name}"]`);
  }
  return range;
}

/**
 * Derives the scaffold's version pins from the engine manifests.
 *
 * Policy:
 *  - @press/* → EXACT (the trio releases together; an adopter's `create` must
 *    match the engine that produced it — a caret on 0.x would silently admit a
 *    breaking minor, which is exactly the drift this codegen kills).
 *  - frameworks → the range the engine itself is tested against: react comes
 *    from @press/web's devDependency (one react major across cms + web — Strapi 5
 *    admin and Next 15 both run React 18, so a dual-major hoist hazard is
 *    avoided), strapi from @press/cms's devDependency, next from NEXT_PIN.
 */
export function computeVersions(m: EngineManifests): ScaffoldVersions {
  return {
    pressCli: m.cli.version,
    pressWeb: m.web.version,
    pressCms: m.cms.version,
    next: NEXT_PIN,
    react: requireDevDep(m.web, 'react', '@press/web'),
    strapi: requireDevDep(m.cms, '@strapi/strapi', '@press/cms'),
  };
}

/** Serializes the pins to the exact TS source committed as versions.generated.ts. */
export function renderVersionsModule(v: ScaffoldVersions): string {
  const entries = Object.entries(v)
    .map(([k, value]) => `  ${k}: '${value}',`)
    .join('\n');
  return (
    [
      '// AUTO-GENERATED by scripts/gen-versions.ts — DO NOT EDIT.',
      '// Regenerate with: pnpm --filter @press/cli gen:versions',
      "// Source of truth: the engine packages' own package.json manifests.",
      '',
    ].join('\n') + `export const VERSIONS = {\n${entries}\n} as const;\n`
  );
}
