// AUTO-GENERATED by @ogs-tech/press-web sync-types — DO NOT EDIT.
// Regenerate with: pnpm --filter @ogs-tech/press-web sync-types

export interface PressMedia {
  url: string;
  width?: number;
  height?: number;
  alternativeText?: string | null;
  name?: string;
  mime?: string;
}

export interface PressHero {
  __component: 'press.hero';
  id: number;
  heading: string;
  subheading?: string;
  ctaLabel?: string;
  image?: PressMedia;
}

export interface CustomCallout {
  __component: 'custom.callout';
  id: number;
  message: string;
  variant?: 'info' | 'warning' | 'success';
}

export type PageBody = (PressHero | CustomCallout)[];

export interface Page {
  id: number;
  documentId: string;
  title: string;
  slug?: string;
  body: PageBody;
}
