// AUTO-GENERATED by @ogs-tech/press-web sync-types — DO NOT EDIT.
// Regenerate with: pnpm --filter @ogs-tech/press-web sync-types

export interface PressMedia {
  url: string;
  width?: number;
  height?: number;
  alternativeText?: string | null;
  name?: string;
  mime?: string;
}

export interface PressParagraph {
  __component: 'press.paragraph';
  id: number;
  content: unknown;
}

export interface PressHeading {
  __component: 'press.heading';
  id: number;
  text: string;
  level: '1' | '2' | '3' | '4' | '5' | '6';
}

export interface PressList {
  __component: 'press.list';
  id: number;
  content: unknown;
}

export interface PressQuote {
  __component: 'press.quote';
  id: number;
  content: unknown;
  citation?: string;
}

export interface PressImage {
  __component: 'press.image';
  id: number;
  image: PressMedia;
  caption?: string;
}

export interface PressButton {
  __component: 'press.button';
  id: number;
  label: string;
  href: string;
  variant: 'primary' | 'secondary';
}

export interface PressSeparator {
  __component: 'press.separator';
  id: number;
  variant: 'line' | 'dots';
}

export interface PressSpacer {
  __component: 'press.spacer';
  id: number;
  size: 'sm' | 'md' | 'lg' | 'xl';
}

export interface CustomCallout {
  __component: 'custom.callout';
  id: number;
  message: string;
  variant?: 'info' | 'warning' | 'success';
}

export type PageBody = (PressParagraph | PressHeading | PressList | PressQuote | PressImage | PressButton | PressSeparator | PressSpacer | CustomCallout)[];

export interface Page {
  id: number;
  documentId: string;
  title: string;
  slug?: string;
  body: PageBody;
}
