// AUTO-GENERATED by @ogs-tech/press-web sync-types — DO NOT EDIT.
// Regenerate with: pnpm --filter @ogs-tech/press-web sync-types

import type { PressTree } from '@ogs-tech/press-web';

export interface PressMedia {
  url: string;
  width?: number;
  height?: number;
  alternativeText?: string | null;
  name?: string;
  mime?: string;
}

export interface PressPageRef {
  documentId: string;
  slug?: string;
}

export interface CustomOrganismCallout {
  message: string;
  variant?: 'info' | 'warning' | 'success';
}

export interface PresetAtomParagraph {
  content: string;
}

export interface PresetAtomHeading {
  text: string;
  level: '1' | '2' | '3' | '4' | '5' | '6';
}

export interface PresetAtomList {
  content: string;
  format?: 'unordered' | 'ordered';
}

export interface PresetAtomQuote {
  content: string;
  citation?: string;
}

export interface PresetAtomImage {
  image: PressMedia;
  caption?: string;
}

export interface PresetAtomButton {
  link?: PresetMoleculeLink;
  variant?: 'primary' | 'secondary';
}

export interface PresetAtomSeparator {
  variant: 'line' | 'dots';
}

export interface PresetAtomSpacer {
  size: 'sm' | 'md' | 'lg' | 'xl';
}

export interface PresetMoleculeLink {
  label?: string;
  page?: PressPageRef;
  url?: string;
  newTab?: boolean;
}

export interface PresetOrganismHero {
  eyebrow?: string;
  title: string;
  subtitle?: string;
  image?: PressMedia;
  cta?: PresetMoleculeLink;
  align?: 'left' | 'center';
}

export interface PresetOrganismCta {
  title: string;
  subtitle?: string;
  button?: PresetMoleculeLink;
  align?: 'left' | 'center';
}

export interface PresetOrganismNavbar {
  items?: PresetMoleculeLink[];
  cta?: PresetAtomButton;
}

export interface PresetOrganismFooter {
  text?: string;
}

export interface PresetLayoutContainer {
  width?: 'prose' | 'lg' | 'full';
  gap?: 'compact' | 'normal' | 'spacious';
  verticalAlign?: 'top' | 'center' | 'bottom';
}

export interface PresetLayoutRow {
  ratio?: '50-50' | '33-67' | '67-33' | '33-33-33' | '25-25-25-25';
  container?: PresetLayoutContainer;
}

export interface PresetLayoutColumn {
  container?: PresetLayoutContainer;
}

export interface PresetConfigSeo {
  titleTemplate?: string;
  title?: string;
  description?: string;
  image?: PressMedia;
}

export interface PresetConfigThemeColors {
  primary?: string;
  accent?: string;
  secondary?: string;
  ink?: string;
  surface?: string;
  muted?: string;
  danger?: string;
  onPrimary?: string;
  border?: string;
}

export interface PresetConfigThemeRadius {
  xs?: string;
  sm?: string;
  md?: string;
  lg?: string;
}

export interface PresetConfigCookieCategory {
  enabled?: boolean;
  label?: string;
  description?: string;
}

export interface PresetConfigCookieConsent {
  enabled?: boolean;
  title?: string;
  description?: string;
  acceptAllLabel?: string;
  rejectAllLabel?: string;
  manageLabel?: string;
  saveLabel?: string;
  privacyLinkLabel?: string;
  privacyPage?: PressPageRef;
  necessary?: PresetConfigCookieCategory;
  analytics?: PresetConfigCookieCategory;
  marketing?: PresetConfigCookieCategory;
}

/** The page body IS the composition tree (composition-builder spec §5). */
export type PageBody = PressTree;

export interface Page {
  id: number;
  documentId: string;
  title: string;
  slug?: string;
  body: PageBody;
}
