/**
 * Pure schema → TypeScript generator. Input is the JSON served by the engine's
 * `/api/press/schema` (the runtime contract). Output is plain, framework-agnostic
 * TS written to src/types/generated.ts. No Strapi types are referenced — the
 * generator is decoupled from Strapi's internal type format on purpose (Spec
 * §5.2 rejected alternative 3).
 */

export interface Attr {
  type: string;
  required?: boolean;
  enum?: string[];
  multiple?: boolean;
  components?: string[];
  [k: string]: unknown;
}

export interface PressSchema {
  contentTypes: Record<string, { uid: string; info: unknown; attributes: Record<string, Attr> }>;
  components: Record<string, { uid: string; attributes: Record<string, Attr> }>;
}

const pascalSegment = (s: string): string =>
  s
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');

/** `press.hero` → `PressHero`, `custom.call-to-action` → `CustomCallToAction`. */
export const pascalForUid = (uid: string): string =>
  uid.split('.').map(pascalSegment).join('');

const SCALARS: Record<string, string> = {
  string: 'string', text: 'string', richtext: 'string', uid: 'string',
  email: 'string', password: 'string', date: 'string', datetime: 'string',
  time: 'string', timestamp: 'string',
  integer: 'number', biginteger: 'number', float: 'number', decimal: 'number',
  boolean: 'boolean', json: 'unknown',
};

/** Maps a single Strapi attribute to its TS type expression. */
export const tsTypeForAttribute = (attr: Attr): string => {
  if (attr.type === 'enumeration' && Array.isArray(attr.enum)) {
    return attr.enum.map((v) => `'${v}'`).join(' | ');
  }
  if (attr.type === 'media') {
    return attr.multiple ? 'PressMedia[]' : 'PressMedia';
  }
  return SCALARS[attr.type] ?? 'unknown';
};

const emitInterfaceBody = (attributes: Record<string, Attr>, indent = '  '): string =>
  Object.entries(attributes)
    .map(([name, attr]) => {
      // DZ inside a component is out of scope for Spec 1; skip if present.
      if (attr.type === 'dynamiczone') return null;
      const optional = attr.required ? '' : '?';
      return `${indent}${name}${optional}: ${tsTypeForAttribute(attr)};`;
    })
    .filter(Boolean)
    .join('\n');

const PRESS_MEDIA = `export interface PressMedia {
  url: string;
  width?: number;
  height?: number;
  alternativeText?: string | null;
  name?: string;
  mime?: string;
}`;

export const generateTypes = (schema: PressSchema): string => {
  const blocks: string[] = [
    '// AUTO-GENERATED by @press/web sync-types — DO NOT EDIT.',
    '// Regenerate with: pnpm --filter @press/web sync-types',
    '',
    PRESS_MEDIA,
    '',
  ];

  const componentTypeNames: Record<string, string> = {};
  for (const [uid, comp] of Object.entries(schema.components)) {
    const name = pascalForUid(uid);
    componentTypeNames[uid] = name;
    blocks.push(
      `export interface ${name} {`,
      `  __component: '${uid}';`,
      `  id: number;`,
      emitInterfaceBody(comp.attributes),
      `}`,
      '',
    );
  }

  // The page content-type (single one in Spec 1).
  const page = Object.values(schema.contentTypes)[0];
  const bodyAttr = page.attributes.body;
  const union = (bodyAttr?.components ?? [])
    .map((uid) => componentTypeNames[uid])
    .filter(Boolean)
    .join(' | ');

  blocks.push(`export type PageBody = (${union || 'never'})[];`, '');

  const pageFields = Object.entries(page.attributes)
    .map(([name, attr]) => {
      if (name === 'body') return `  body: PageBody;`;
      const optional = attr.required ? '' : '?';
      return `  ${name}${optional}: ${tsTypeForAttribute(attr)};`;
    })
    .join('\n');

  blocks.push(
    `export interface Page {`,
    `  id: number;`,
    `  documentId: string;`,
    pageFields,
    `}`,
    '',
  );

  return blocks.join('\n');
};
