// AUTO-GENERATED by @ogs-tech/press-web sync-types — DO NOT EDIT.
// Regenerate with: pnpm --filter @ogs-tech/press-web sync-types

import type { PressTree } from '@ogs-tech/press-web';

export interface PressMedia {
  url: string;
  width?: number;
  height?: number;
  alternativeText?: string | null;
  name?: string;
  mime?: string;
}

export interface PressPageRef {
  documentId: string;
  slug?: string;
}

export interface PresetAtomParagraph {
  content: string;
}

export interface PresetAtomHeading {
  text: string;
  level: '1' | '2' | '3' | '4' | '5' | '6';
}

export interface PresetAtomList {
  content: string;
  format?: 'unordered' | 'ordered';
}

export interface PresetAtomQuote {
  content: string;
  citation?: string;
}

export interface PresetAtomImage {
  image: PressMedia;
  caption?: string;
}

export interface PresetAtomButton {
  link?: PresetMoleculeLink;
  variant?: 'primary' | 'secondary';
}

export interface PresetAtomSeparator {
  variant?: 'line' | 'dots';
}

export interface PresetAtomSpacer {
  size?: 'sm' | 'md' | 'lg' | 'xl';
}

export interface PresetMoleculeLink {
  label?: string;
  page?: PressPageRef;
  url?: string;
  newTab?: boolean;
}

export interface PresetLayoutContainer {
  width?: 'prose' | 'lg' | 'full';
  gap?: 'compact' | 'normal' | 'spacious';
  verticalAlign?: 'top' | 'center' | 'bottom';
}

export interface PresetLayoutRow {
  container?: PresetLayoutContainer;
}

export interface PresetLayoutColumn {
  container?: PresetLayoutContainer;
}

export interface PresetOrganismHero {
  eyebrow?: string;
  title: string;
  subtitle?: string;
  image?: PressMedia;
  cta?: PresetMoleculeLink;
  align?: 'left' | 'center';
}

export interface PresetOrganismCta {
  title: string;
  subtitle?: string;
  button?: PresetMoleculeLink;
  align?: 'left' | 'center';
}

export interface PresetOrganismNavbar {
  items?: PresetMoleculeLink[];
  cta?: PresetAtomButton;
}

export interface PresetOrganismFooter {
  text?: string;
}

export interface CustomOrganismCallout {
  message: string;
  variant?: 'info' | 'warning' | 'success';
}

/** The page body IS the composition tree (composition-builder spec §5). */
export type PageBody = PressTree;

export interface Page {
  id: number;
  documentId: string;
  title: string;
  slug?: string;
  body: PageBody;
}
