/**
 * Pure schema → TypeScript generator. Input is the JSON served by the engine's
 * `/api/press/schema` (the runtime contract). Output is plain, framework-agnostic
 * TS written to the adopter's shared/types/generated.ts. No Strapi types are referenced — the
 * generator is decoupled from Strapi's internal type format on purpose (Spec
 * §5.2 rejected alternative 3).
 */

import type { Attr, PressSchema } from '@ogs-tech/press-shared';

// Re-exported so existing consumers (bin/sync-types) keep their import path.
export type { Attr, PressSchema };

const pascalSegment = (s: string): string =>
  s
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');

/** `press.paragraph` → `PressParagraph`, `custom.call-to-action` → `CustomCallToAction`. */
export const pascalForUid = (uid: string): string =>
  uid.split('.').map(pascalSegment).join('');

const SCALARS: Record<string, string> = {
  string: 'string', text: 'string', richtext: 'string', uid: 'string',
  email: 'string', password: 'string', date: 'string', datetime: 'string',
  time: 'string', timestamp: 'string',
  integer: 'number', biginteger: 'number', float: 'number', decimal: 'number',
  boolean: 'boolean', json: 'unknown',
};

const PAGE_UID = 'plugin::press-cms.page';
const SITE_SETTING_UID = 'plugin::press-cms.site-setting';

/** Maps a single Strapi attribute to its TS type expression. */
export const tsTypeForAttribute = (attr: Attr): string => {
  if (attr.type === 'enumeration' && Array.isArray(attr.enum)) {
    return attr.enum.length
      ? attr.enum.map((v) => `'${v}'`).join(' | ')
      : 'never';
  }
  if (attr.type === 'component' && typeof attr.component === 'string') {
    // A nested component reference (Spec §2). NOTE: Strapi sends no __component
    // discriminator for nested components; when the referenced component is also
    // a DZ member (so its interface carries __component), the nested value simply
    // omits that field on the wire — never discriminate a nested value on it.
    const ref = pascalForUid(attr.component);
    return attr.repeatable ? `${ref}[]` : ref;
  }
  if (attr.type === 'media') {
    return attr.multiple ? 'PressMedia[]' : 'PressMedia';
  }
  return (attr.type ? SCALARS[attr.type] : undefined) ?? 'unknown';
};

const emitInterfaceBody = (attributes: Record<string, Attr>, indent = '  '): string =>
  Object.entries(attributes)
    .map(([name, attr]) => {
      // DZ inside a component is out of scope for Spec 1; skip if present.
      if (attr.type === 'dynamiczone') return null;
      // Relations are out of generator scope (Spec §2): the nav-item `page`
      // relation is resolved at runtime by the web side, never consumed raw.
      if (attr.type === 'relation') return null;
      const optional = attr.required ? '' : '?';
      return `${indent}${name}${optional}: ${tsTypeForAttribute(attr)};`;
    })
    .filter(Boolean)
    .join('\n');

const PRESS_MEDIA = `export interface PressMedia {
  url: string;
  width?: number;
  height?: number;
  alternativeText?: string | null;
  name?: string;
  mime?: string;
}`;

export const generateTypes = (schema: PressSchema): string => {
  const blocks: string[] = [
    '// AUTO-GENERATED by @ogs-tech/press-web sync-types — DO NOT EDIT.',
    '// Regenerate with: pnpm --filter @ogs-tech/press-web sync-types',
    '',
    PRESS_MEDIA,
    '',
  ];

  const page = schema.contentTypes[PAGE_UID] ?? Object.values(schema.contentTypes)[0];
  const siteSetting = schema.contentTypes[SITE_SETTING_UID];

  const bodyUids = page.attributes.body?.components ?? [];
  const headerUids = siteSetting?.attributes.header?.components ?? [];
  const footerUids = siteSetting?.attributes.footer?.components ?? [];
  // Strapi sends the __component discriminator ONLY for dynamic-zone entries; a
  // component that appears solely nested inside another must not claim one (Spec §2).
  const dzMembers = new Set([...bodyUids, ...headerUids, ...footerUids]);

  const componentTypeNames: Record<string, string> = {};
  for (const [uid, comp] of Object.entries(schema.components)) {
    const name = pascalForUid(uid);
    componentTypeNames[uid] = name;
    blocks.push(
      `export interface ${name} {`,
      ...(dzMembers.has(uid) ? [`  __component: '${uid}';`] : []),
      `  id: number;`,
      emitInterfaceBody(comp.attributes),
      `}`,
      '',
    );
  }

  const union = (uids: string[]): string =>
    uids.map((uid) => componentTypeNames[uid]).filter(Boolean).join(' | ');

  blocks.push(`export type PageBody = (${union(bodyUids) || 'never'})[];`, '');

  // Chrome DZ unions (Spec §2). Emitted only when the cms serves the site-setting
  // entry — an older press-cms without chrome must not break type-sync.
  if (siteSetting) {
    blocks.push(`export type HeaderBlocks = (${union(headerUids) || 'never'})[];`, '');
    blocks.push(`export type FooterBlocks = (${union(footerUids) || 'never'})[];`, '');
  }

  const pageFields = Object.entries(page.attributes)
    .map(([name, attr]) => {
      if (name === 'body') return `  body: PageBody;`;
      const optional = attr.required ? '' : '?';
      return `  ${name}${optional}: ${tsTypeForAttribute(attr)};`;
    })
    .join('\n');

  blocks.push(
    `export interface Page {`,
    `  id: number;`,
    `  documentId: string;`,
    pageFields,
    `}`,
    '',
  );

  return blocks.join('\n');
};
