/**
 * Pure schema → TypeScript generator. Input is the JSON served by the engine's
 * `/api/press/schema` (the runtime contract). Output is plain, framework-agnostic
 * TS written to the adopter's shared/types/generated.ts. No Strapi types are referenced — the
 * generator is decoupled from Strapi's internal type format on purpose (Spec
 * §5.2 rejected alternative 3).
 */

import type { Attr, PressSchema } from '@ogs-tech/press-shared';

// Re-exported so existing consumers (bin/sync-types) keep their import path.
export type { Attr, PressSchema };

const pascalSegment = (s: string): string =>
  s
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');

/** `preset-atom.paragraph` → `PresetAtomParagraph`, `custom-organism.call-to-action` → `CustomOrganismCallToAction`. */
export const pascalForUid = (uid: string): string =>
  uid.split('.').map(pascalSegment).join('');

const SCALARS: Record<string, string> = {
  string: 'string', text: 'string', richtext: 'string', uid: 'string',
  email: 'string', password: 'string', date: 'string', datetime: 'string',
  time: 'string', timestamp: 'string',
  integer: 'number', biginteger: 'number', float: 'number', decimal: 'number',
  boolean: 'boolean', json: 'unknown',
};

const PAGE_UID = 'plugin::press-cms.page';

/** Maps a single Strapi attribute to its TS type expression. */
export const tsTypeForAttribute = (attr: Attr): string => {
  if (attr.type === 'enumeration' && Array.isArray(attr.enum)) {
    return attr.enum.length
      ? attr.enum.map((v) => `'${v}'`).join(' | ')
      : 'never';
  }
  if (attr.type === 'component' && typeof attr.component === 'string') {
    // A nested component reference (Spec §2). Strapi sends no __component
    // discriminator for nested components (nor, in the tree world, for any
    // component — tree `data` objects carry neither `__component` nor `id`).
    const ref = pascalForUid(attr.component);
    return attr.repeatable ? `${ref}[]` : ref;
  }
  if (attr.type === 'media') {
    return attr.multiple ? 'PressMedia[]' : 'PressMedia';
  }
  if (attr.type === 'relation') {
    // Only the page-picker relation (nav-item/link `page` field) is consumed:
    // the cms hydrates it into a PressPageRef. Every other relation stays out
    // of generator scope (Spec §2) and is skipped at emit below.
    return (attr as Record<string, unknown>).target === 'plugin::press-cms.page' ? 'PressPageRef' : 'unknown';
  }
  return (attr.type ? SCALARS[attr.type] : undefined) ?? 'unknown';
};

const emitInterfaceBody = (attributes: Record<string, Attr>, indent = '  '): string =>
  Object.entries(attributes)
    .map(([name, attr]) => {
      // DZ inside a component is out of scope for Spec 1; skip if present.
      if (attr.type === 'dynamiczone') return null;
      // Non-page relations are out of generator scope (Spec §2): resolved at
      // runtime by the web side, never consumed raw. The page-picker relation
      // is emitted as PressPageRef (see tsTypeForAttribute).
      if (attr.type === 'relation' && (attr as Record<string, unknown>).target !== 'plugin::press-cms.page') return null;
      const optional = attr.required ? '' : '?';
      return `${indent}${name}${optional}: ${tsTypeForAttribute(attr)};`;
    })
    .filter(Boolean)
    .join('\n');

const PRESS_MEDIA = `export interface PressMedia {
  url: string;
  width?: number;
  height?: number;
  alternativeText?: string | null;
  name?: string;
  mime?: string;
}`;

const PAGE_REF = `export interface PressPageRef {
  documentId: string;
  slug?: string;
}`;

export const generateTypes = (schema: PressSchema): string => {
  const blocks: string[] = [
    '// AUTO-GENERATED by @ogs-tech/press-web sync-types — DO NOT EDIT.',
    '// Regenerate with: pnpm --filter @ogs-tech/press-web sync-types',
    '',
    "import type { PressTree } from '@ogs-tech/press-web';",
    '',
    PRESS_MEDIA,
    '',
    PAGE_REF,
    '',
  ];

  const page = schema.contentTypes[PAGE_UID] ?? Object.values(schema.contentTypes)[0];

  // Tree world: every component is a plain `data` object (composition-builder
  // spec §5) — no DZ membership, no __component discriminator, no row id.
  for (const [uid, comp] of Object.entries(schema.components)) {
    const name = pascalForUid(uid);
    blocks.push(`export interface ${name} {`, emitInterfaceBody(comp.attributes), `}`, '');
  }

  blocks.push('/** The page body IS the composition tree (composition-builder spec §5). */');
  blocks.push(`export type PageBody = PressTree;`, '');

  const pageFields = Object.entries(page.attributes)
    .map(([name, attr]) => {
      // Always PageBody by field name — never gated on the customField id,
      // which the real serializer strips (KEEP list omits `customField`).
      if (name === 'body') return `  body: PageBody;`;
      const optional = attr.required ? '' : '?';
      return `  ${name}${optional}: ${tsTypeForAttribute(attr)};`;
    })
    .join('\n');

  blocks.push(
    `export interface Page {`,
    `  id: number;`,
    `  documentId: string;`,
    pageFields,
    `}`,
    '',
  );

  return blocks.join('\n');
};
